image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - Hridoy.rails-snippets@1.0.8:RFZBiddbEeItUesTv9F11w==
    - vortizhe.simple-ruby-erb@0.2.1:BzpDuNAqJwUkxqT2t1YIuQ==
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
    - castwide.ruby-debug@0.3.5:aUfPz6hreQXuO01QqjhpLQ==
    - rebornix.ruby@0.26.0:RN+gv0dPjYfMqlcEEralhg==
    - PKief.material-icon-theme@3.9.3:GVmljEI1+vB8Qkqq/e1dfw==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - idleberg.hopscotch@0.2.2:3P7ooJ+d2L/nCC3VkcfbhA==